#pragma once
#include <Windows.h>

namespace NativeExtractor {

	const UINT SUCCESS = 0x00;
	const UINT FILE_NOT_FOUND_OR_INVALID = 0x01;
	const UINT FAILED_TO_OPEN_STREAM = 0x02;
	const UINT WINDOW_NOT_FOUND = 0x03;
	const UINT OPEN_PROCESS_FAILED = 0x04;
	const UINT MODULE_RETRIEVAL_FAILED = 0x05;
	const UINT IMAGE_FILENAME_NOT_FOUND = 0x06;
	const UINT MAIN_MODULE_NOT_FOUND = 0x07;
	const UINT MODULE_INFO_RETRIEVAL_FAILED = 0x08;
	const UINT MEMORY_ALLOCATION_FAILED = 0x09;
	const UINT REMOTE_READ_FAILED = 0x0A;
	const UINT SIGNATURE_SCAN_FAILED = 0x0B;
	const UINT FILE_EXISTS = 0x0C;

}